# Generated by Django 5.1.3 on 2024-11-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Введите название курса', max_length=100, verbose_name='Название курса')),
                ('course_description', models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание курса')),
                ('course_picture', models.ImageField(blank=True, help_text='Загрузите картинку курса', null=True, upload_to='materials/photo', verbose_name='Превью курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(help_text='Введите название урока', max_length=100, verbose_name='Название урока')),
                ('lesson_description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание урока')),
                ('lesson_picture', models.ImageField(blank=True, help_text='Загрузите картинку урока', null=True, upload_to='materials/photo', verbose_name='Превью урока')),
                ('video_link', models.URLField(blank=True, help_text='Добавьте ссылку на видео', max_length=300, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Введите название курса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
